### ISSUE TITLE
broken tint2 and rofi config on openbox

### ISSUE THREAD

**Issue by carnivorecookies** [CachyOS/cachyos-openbox-settings#1]
if you set your primary monitor to something other than default using arandr or xrandr, when you try to maximize a window in the non-primary monitor, it bugs out and tiles itself into the primary monitor. (tint2)

with rofi, instead of the text being slightly to the right, it is centered in the prompt. not sure why

steps to produce:

1. have 2 monitors
2. log into openbox
3. run the following command: `xrandr --output current_non_primary_monitor --primary`
4. open rofi to see the text bug
5. drag one of your windows to the now non-primary monitor, and then double click the window titlebar. itll bug out

**Comment by carnivorecookies** [comment]
Looks like this bug IS FIXED (with some wonkiness such as uneven gaps) if you set the bar to be horizontal, or if you enable mechanical mode. Not closing since it still occurs on a vertical bar

**Comment by carnivorecookies** [comment]
EDIT: changing monitors doesnt cause it. having 2 monitors causes the issue

**Comment by ptr1337** [comment]
Hi,

I think you should generally report this to https://github.com/owl4ce/dotfiles . From there we use the dotfiles and the owner knows that.
@owl4ce can you help there? Im really not much into openbox

**Comment by owl4ce** [comment]
Sorry, a bit busy here. As far as I know, Openbox has always had problems with multi-monitors, in my case I was using single-monitor, so I couldn't reproduce the issue. I will continue this later ...

**Comment by owl4ce** [comment]
Probably, removing Openbox gaps fixes the issue (?)
---
This line
https://github.com/CachyOS/cachyos-openbox-settings/blob/9750271d5024e88d14a485e2ff8ee709828bd9e5/etc/skel/.joyfuld#L186
will synchronize
https://github.com/CachyOS/cachyos-openbox-settings/blob/9750271d5024e88d14a485e2ff8ee709828bd9e5/etc/skel/.config/openbox/rc.xml#L151-L156

which executed by
https://github.com/CachyOS/cachyos-openbox-settings/blob/9750271d5024e88d14a485e2ff8ee709828bd9e5/etc/skel/.config/openbox/joyful-desktop/layout-set.sh#L1-L99

**Comment by owl4ce** [comment]
Set it to zero (`0`) instead.

**Comment by carnivorecookies** [comment]
Appears to be (almost) fixed
Maximization is normal, but as soon as you change back to vertical bar from horizontal bar, the maximized window goes back to the primary monitor as a regular maximized windows

When i made the post, it would originally tile to the primary monitor with vertical bar. there were also some weird gap issues on the non-primary monitor when maximizing w/ horizontal bar

**Comment by carnivorecookies** [comment]
i actually think it might be a tint2 issue, iirc this was a bug reported to tint2 at one point
either way, it appears to be a tint2 or openbox issue so i'll close this
